// source: user.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var google_protobuf_empty_pb = require('google-protobuf/google/protobuf/empty_pb.js');
goog.object.extend(proto, google_protobuf_empty_pb);
var common_pb = require('./common_pb.js');
goog.object.extend(proto, common_pb);
goog.exportSymbol('proto.UserMedCommon', null, global);
goog.exportSymbol('proto.UserMedInfo', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.UserMedCommon = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.UserMedCommon, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.UserMedCommon.displayName = 'proto.UserMedCommon';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.UserMedInfo = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.UserMedInfo, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.UserMedInfo.displayName = 'proto.UserMedInfo';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.UserMedCommon.prototype.toObject = function(opt_includeInstance) {
  return proto.UserMedCommon.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.UserMedCommon} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.UserMedCommon.toObject = function(includeInstance, msg) {
  var f, obj = {
    height: jspb.Message.getFieldWithDefault(msg, 1, 0),
    weight: jspb.Message.getFieldWithDefault(msg, 2, 0),
    preshigh: jspb.Message.getFieldWithDefault(msg, 3, 0),
    preslow: jspb.Message.getFieldWithDefault(msg, 4, 0),
    sightleft: jspb.Message.getFieldWithDefault(msg, 5, ""),
    sightright: jspb.Message.getFieldWithDefault(msg, 6, ""),
    smoke: jspb.Message.getFieldWithDefault(msg, 7, ""),
    family: jspb.Message.getFieldWithDefault(msg, 8, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.UserMedCommon}
 */
proto.UserMedCommon.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.UserMedCommon;
  return proto.UserMedCommon.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.UserMedCommon} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.UserMedCommon}
 */
proto.UserMedCommon.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setHeight(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setWeight(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setPreshigh(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setPreslow(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setSightleft(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setSightright(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setSmoke(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.setFamily(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.UserMedCommon.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.UserMedCommon.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.UserMedCommon} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.UserMedCommon.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getHeight();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = message.getWeight();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getPreshigh();
  if (f !== 0) {
    writer.writeInt32(
      3,
      f
    );
  }
  f = message.getPreslow();
  if (f !== 0) {
    writer.writeInt32(
      4,
      f
    );
  }
  f = message.getSightleft();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getSightright();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getSmoke();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getFamily();
  if (f.length > 0) {
    writer.writeString(
      8,
      f
    );
  }
};


/**
 * optional int32 height = 1;
 * @return {number}
 */
proto.UserMedCommon.prototype.getHeight = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.UserMedCommon} returns this
 */
proto.UserMedCommon.prototype.setHeight = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional int32 weight = 2;
 * @return {number}
 */
proto.UserMedCommon.prototype.getWeight = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.UserMedCommon} returns this
 */
proto.UserMedCommon.prototype.setWeight = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional int32 presHigh = 3;
 * @return {number}
 */
proto.UserMedCommon.prototype.getPreshigh = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.UserMedCommon} returns this
 */
proto.UserMedCommon.prototype.setPreshigh = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional int32 presLow = 4;
 * @return {number}
 */
proto.UserMedCommon.prototype.getPreslow = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.UserMedCommon} returns this
 */
proto.UserMedCommon.prototype.setPreslow = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional string sightLeft = 5;
 * @return {string}
 */
proto.UserMedCommon.prototype.getSightleft = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.UserMedCommon} returns this
 */
proto.UserMedCommon.prototype.setSightleft = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string sightRight = 6;
 * @return {string}
 */
proto.UserMedCommon.prototype.getSightright = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.UserMedCommon} returns this
 */
proto.UserMedCommon.prototype.setSightright = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional string smoke = 7;
 * @return {string}
 */
proto.UserMedCommon.prototype.getSmoke = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.UserMedCommon} returns this
 */
proto.UserMedCommon.prototype.setSmoke = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * optional string family = 8;
 * @return {string}
 */
proto.UserMedCommon.prototype.getFamily = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/**
 * @param {string} value
 * @return {!proto.UserMedCommon} returns this
 */
proto.UserMedCommon.prototype.setFamily = function(value) {
  return jspb.Message.setProto3StringField(this, 8, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.UserMedInfo.prototype.toObject = function(opt_includeInstance) {
  return proto.UserMedInfo.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.UserMedInfo} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.UserMedInfo.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: (f = msg.getId()) && common_pb.UserId.toObject(includeInstance, f),
    data: (f = msg.getData()) && proto.UserMedCommon.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.UserMedInfo}
 */
proto.UserMedInfo.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.UserMedInfo;
  return proto.UserMedInfo.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.UserMedInfo} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.UserMedInfo}
 */
proto.UserMedInfo.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new common_pb.UserId;
      reader.readMessage(value,common_pb.UserId.deserializeBinaryFromReader);
      msg.setId(value);
      break;
    case 2:
      var value = new proto.UserMedCommon;
      reader.readMessage(value,proto.UserMedCommon.deserializeBinaryFromReader);
      msg.setData(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.UserMedInfo.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.UserMedInfo.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.UserMedInfo} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.UserMedInfo.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      common_pb.UserId.serializeBinaryToWriter
    );
  }
  f = message.getData();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.UserMedCommon.serializeBinaryToWriter
    );
  }
};


/**
 * optional UserId id = 1;
 * @return {?proto.UserId}
 */
proto.UserMedInfo.prototype.getId = function() {
  return /** @type{?proto.UserId} */ (
    jspb.Message.getWrapperField(this, common_pb.UserId, 1));
};


/**
 * @param {?proto.UserId|undefined} value
 * @return {!proto.UserMedInfo} returns this
*/
proto.UserMedInfo.prototype.setId = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.UserMedInfo} returns this
 */
proto.UserMedInfo.prototype.clearId = function() {
  return this.setId(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.UserMedInfo.prototype.hasId = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional UserMedCommon data = 2;
 * @return {?proto.UserMedCommon}
 */
proto.UserMedInfo.prototype.getData = function() {
  return /** @type{?proto.UserMedCommon} */ (
    jspb.Message.getWrapperField(this, proto.UserMedCommon, 2));
};


/**
 * @param {?proto.UserMedCommon|undefined} value
 * @return {!proto.UserMedInfo} returns this
*/
proto.UserMedInfo.prototype.setData = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.UserMedInfo} returns this
 */
proto.UserMedInfo.prototype.clearData = function() {
  return this.setData(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.UserMedInfo.prototype.hasData = function() {
  return jspb.Message.getField(this, 2) != null;
};


goog.object.extend(exports, proto);
